language: python

env:
    - DJANGO_SETTINGS_MODULE='bctf.settings.development'

python:
    - 3.6

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - pycodestyle --ignore E501 apps
    - coverage run manage.py test -v 2
    
after_success:
    - coverage report
