language: python
services:
    - docker
env:
    - DJANGO_SETTINGS_MODULE='bctf.settings.development'
python:
    - 3.6
install:
    - pip install -r requirements.txt
script:
    - coverage run manage.py tests -v 2
after_success:
- coverage report
