image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - coverage run manage.py tests -v 2
          - coverage report
