version: "3"

services:
  web:
    build: .
    container_name: bctf-app
    restart: always
    env_file:
      - ./.env
      - ./.env.secret
    command: gunicorn --bind 0.0.0.0:8080 dockerizeddjango.wsgi
    volumes:
      - .:/www
    ports:
      - "8080:8080"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    container_name: bctf-nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
    ports:
      - "80:80"