version: "3"

services:
  
  web:
    build: .
    container_name: bctf-app
    restart: always
    volumes:
      - .data/media:/app/bctf/media
    ports:
      - "8000:8000"

  nginx:
    image: "nginx"
    container_name: bctf-nginx
    restart: always
    volumes:
      - .data/media:/media
      - ./resources/nginx/sites-enabled/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - web

