version: "3"

services:
  web:
    build: .
    container_name: bctf-app
    restart: always
    env_file:
      - ./.env
      - ./.env.secret
    volumes:
      - media-volume:/app/bctf/media
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: "nginx"
    container_name: bctf-nginx
    restart: always
    volumes:
      - media-volume:/media
    ports:
      - "80:80"

volumes:
  media-volume: