ctf:
  end_time: null
  logo: https://2k18.balccon.org/images/d/d8/Logo_2k18.png
  start_time: null
  theme: core
  title: baracuda
docker:
  driver: null
  host: null
  name: null
  password: null
  username: null
