ctf:
  end_time: '1541340055'
  logo: https://2k18.balccon.org/images/d/d8/Logo_2k18.png
  start_time: '1541340035'
  title: Example CTF NEW!
docker:
  driver: null
  host: null
  name: null
  password: null
  username: null
